from speech import pytts

def demo():
    pytts("Hello!")
    pytts("I am Benji, your personal virtual assistant.")
    pytts("I am a sentient AI created with the Python programming language, and can understand ethical, logical, and psycological problems.")
    pytts("If you ever have a logical question, such as 'who is the first president of china', or 'what is 234 multiplied by 79', don't hesitate to ask!")
    pytts("Furthermore, if you told me some options to a problem you had I could provide you with the best choice. Just say, 'I have a problem'.")
    pytts("In addition to this, I have full access to the internet, so if you need a fact, such as the weather today, or the date, I would happily supply.")
    pytts("Some other things I can do are:")
    pytts("Open Microsoft Word, Powerpoint, or Excel.")
    pytts("Open any website on your default browser.")
    pytts("Get the top news for today.")
    pytts("Play a song.")
    pytts("And finally and most importantly, I am programmed with a shortcut ability, which you can access by telling me to 'open the shortcut manager.'")
    pytts("The shortcut manager is a way for me to perform more specific actions. It lets you program custom shortcuts, and specify a voice command, so that whenever you use that command, I can run your specified shortcut.")
    pytts("I am also programmed with efficient chatbot technology, so if you want, you can have a conversation with me.")
    pytts("So, that's a quick taste of what I can do. Let me know if you need anything.")
    pytts("Just say my name, and I will be there for you.")
    pytts("Benji. Making your life. the best it can be.")
